---
title: "Project_Summary_and_Organization"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Temperature Data

Bristol Bay data providers and data sets. 

Metadata and data ready:

* UAA-ACCS. We have data from 14 sites 2015-2019. We may have installed loggers at a few of our long term sites in 2014 or earlier. Dan Bogan archived all Bristol Bay data on KNB through 2017. I have data from all 14 sites for three downloads after 2017: June 2018, June 2019, and October 2019. Data were finalized in separate repo for our temperature monitoring work, [Bristol-Bay-Temperature](https://github.com/rsshaftel/Bristol-Bay-Temperature).
* NPS. Krista Bartz has sent all data from their Southwest Monitoring Network, including lake arrays. Data have been QAed after emailing questions to Krista - all metadata and data are finel. 
* UWFWS. Meg has shared all FWS data for the State. We will be using data from Togiak refuge and Egegik and Newhalen Rivers. Meg has also sent over lake data.
* Cook Inletkeeper. Sue has provided QAed data from village and lodge partners.

Data need reviewing:

* University of Washington. Jackie Carter has provided metadata and data for streams through 2020. The data are provided as two sets - through 2017 and 2018-2020.  Metadata is ready. Data are formatted, but lots of anomalous data need flagging.
* new NPS data from Krista and Paul -- ~ 10 sites submitted by Dan Young to AKOATS.

Data need to be imported, formatted, and reviewed:

* USGS. Site numbers can be identified on NWIS online and data can be downloaded using dataRetrieval library in R.

Data is requested but not received yet:

* lake data from UW.
* data from 

# Temperature cleaning

The plan is to import data from each provider and format it consistently so that it can be imported into AKTEMP and also merged for this project. There will be a data table and a metadata table for the sites from each provider. The SiteID field will be unique for each dataset (i.e. data from one provider) and can be used to link the information between the two tables. (Note: when data are brought into AKTEMP, the SiteID must  be unique across all providers. When needed, we will add a numeric suffix to make a SiteID unique, but will maintain the SiteID name from the data provider in the sites table in AKTEMP as well.)

Data table:

* SiteID - this should be the original site id as provided by the agency. 
* sampleDate - Date class.
* sampleTime - hms class.
* Temperature - numeric.
* useData - this should be a 0/1. I set everything mutate(useData = 1) first. If some data don't look clean (e.g. air temps or really dampened daily variation indicating burial), we can talk about scripts for setting useData = 0.

Metadata table:

* SiteID - this should be the original site id as provided by the agency.
* AKOATS_ID - when this is available. Some sites may be new and not in AKOATS. Possibly only one ID will be in the data tables, either AKOATS or a SiteID and it may be necessary to read in a separate metadata sheet to link the two.
* Source_Name - name of agency or organization.
* Contact_Person - name of data provider.
* Latitude 
* Longitude


# Temperature Summary

* Number of sites and years of data from each site.
* Time series of mean daily temperatures for streams and lakes, by watershed? If not too busy, would be interesting to see general patterns.
* Calculate simple summary metrics and make some figures.
* Map showing locations of sites across the bay. Maybe also add watershed boundaries for 9 major rivers. In R or ArcGIS.

# Original data stored on google drive
https://drive.google.com/drive/u/3/folders/1XQ2rkLnbsHB_hTaNCUnd6u8-iO_cuuNV
